//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class BuffActionControlConfig: Bright.Config.BeanBase
{
    public BuffActionControlConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ActionControl = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ActionControl.Add(_e0);}}
        PostInit();
    }

    public static BuffActionControlConfig DeserializeBuffActionControlConfig(ByteBuf _buf)
    {
        return new BuffActionControlConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 行为禁制
    /// </summary>
    public System.Collections.Generic.List<int> ActionControl { get; private set; }

    public const int __ID__ = -2046991114;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ActionControl:" + Bright.Common.StringUtil.CollectionToString(ActionControl) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}