//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class BuffBleedConfig: Bright.Config.BeanBase
{
    public BuffBleedConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        FormulaId = _buf.ReadInt();
        CD = _buf.ReadInt();
        PostInit();
    }

    public static BuffBleedConfig DeserializeBuffBleedConfig(ByteBuf _buf)
    {
        return new BuffBleedConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 计算公式
    /// </summary>
    public int FormulaId { get; private set; }
    /// <summary>
    /// 出血间隔
    /// </summary>
    public int CD { get; private set; }

    public const int __ID__ = -1924732759;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "FormulaId:" + FormulaId + ","
        + "CD:" + CD + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}