//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class BuffChantConfig: Bright.Config.BeanBase
{
    public BuffChantConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MoveInterrupt = _buf.ReadInt();
        DamageInterrupt = _buf.ReadInt();
        BackCoolingPermillage = _buf.ReadInt();
        BackCostPermillage = _buf.ReadInt();
        PostInit();
    }

    public static BuffChantConfig DeserializeBuffChantConfig(ByteBuf _buf)
    {
        return new BuffChantConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 是否移动打断
    /// </summary>
    public int MoveInterrupt { get; private set; }
    /// <summary>
    /// 是否受击打断
    /// </summary>
    public int DamageInterrupt { get; private set; }
    /// <summary>
    /// 打断返回冷却千分比
    /// </summary>
    public int BackCoolingPermillage { get; private set; }
    /// <summary>
    /// 打断返回消耗千分比
    /// </summary>
    public int BackCostPermillage { get; private set; }

    public const int __ID__ = -180198703;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "MoveInterrupt:" + MoveInterrupt + ","
        + "DamageInterrupt:" + DamageInterrupt + ","
        + "BackCoolingPermillage:" + BackCoolingPermillage + ","
        + "BackCostPermillage:" + BackCostPermillage + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}